pipeline {
    agent { label 'onprem-ai-services-4-spyre-cards' }

    environment {
        PROJECT_NAME = 'project-ai-services'
        AI_SERVICES_DIR = 'ai-services'
        AI_SERVICES_BINARY = './bin/ai-services'
        SLACK_NOTIFICATION_CHANNEL = '#jenkins-pr-preview'
        RAG_CHAT_BOT_PORT = '4000'
        AI_SERVICES_REPO_URL = 'https://github.com/IBM/project-ai-services.git'

        RAG_APP_NAME = 'rag-dev'
        // Holding pipeline for configured minutes, to allow user to complete testing
        MAX_APP_RUN_TIME_IN_MINS = '120'
        TEAM_DOMAIN = credentials('team-domain')

        POLLER_LOGS = '/root/cicd/queue_poller.logs'
        POLLER_SCRIPT = '/root/cicd/queue_poller.sh'
        POLLER_TIMEOUT_IN_MINS = '150'
    }

    // Using options to allow one deployment at any given point of time.
    options {
        disableConcurrentBuilds()
    }

    parameters {
        string(
            name: 'CHECKOUT',
            description: 'Please provide the PR number or commit hash value.',
        )
        // If no selection is made, the deployment will proceed based on the code changes.
        choice(
            name: 'DEPLOY_APP',
            choices: ['auto', 'rag-dev'],
            description: 'Select the application to deploy',
        )
    }

    stages {
        stage('Pre Steps') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'jenkins-api',
                    usernameVariable: 'username',
                    passwordVariable: 'password',
                )]) {
                    sh '''
                    nohup $POLLER_SCRIPT $JENKINS_URL CHECKOUT=$CHECKOUT $BUILD_NUMBER $username $password $POLLER_TIMEOUT_IN_MINS >> $POLLER_LOGS 2>&1 &
                    echo "Queue poller process id: $!"
                    '''
                }
                script {
                    if (!params.CHECKOUT.trim()) {
                        error('PR number or commit hash must be provided')
                    }
                    if(params.DEPLOY_APP) {
                        env.APP_NAME = "${params.DEPLOY_APP}-cicd"
                    }
                }
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                script {
                    repoCheckout(params.CHECKOUT)
                }
            }
        }

        stage('Modified App') {
            when { expression { params.DEPLOY_APP == 'auto' } }
            steps {
                script {
                    println 'No app is selected for deployment.'
                    println 'Identifying which application is modified in the branch.'

                    def modifiedApp = getModifiedApp()
                    if (modifiedApp) {
                        env.APP_NAME = "${modifiedApp}-cicd"
                        env.DEPLOY_APP = "${modifiedApp}"
                        println "${env.APP_NAME} app is going to deployed"
                    } else {
                        error('No app is selected or modified in branch for deployment.')
                    }
                }
            }
        }

        // Build image locally, if image is modified
        stage('Build Images') {
            steps {
                script {
                    if (env.DEPLOY_APP == env.RAG_APP_NAME) {
                        buildAppImage(env.RAG_APP_NAME)
                    } else {
                        println 'Skipping rebuilding images of the application.'
                    }
                }
            }
        }

        stage('Build AI Services Binary') {
            steps {
                script {
                    dir("${PROJECT_NAME}/${AI_SERVICES_DIR}") {
                        sh "make build"
                        sh "${AI_SERVICES_BINARY} --version"
                    }
                }
            }
        }

        stage('Delete CICD App') {
            steps{
                script {
                    deleteCicdApp()
                }
            }
        }

        stage('Deployment') {
            steps {
                script {
                    dir("${env.PROJECT_NAME}/${env.AI_SERVICES_DIR}") {
                        sh "${env.AI_SERVICES_BINARY} application ps"
                        sh "${env.AI_SERVICES_BINARY} application create ${env.APP_NAME} -t ${env.DEPLOY_APP} --params ui.port=${env.RAG_CHAT_BOT_PORT} --skip-validation numa"
                    }
                }
            }
        }

        stage('Ingest Document') {
            steps {
                script {
                    sh "cp -r /root/cicd-app-doc/${APP_NAME}/* /var/lib/ai-services/applications/${APP_NAME}/docs/"
                    println 'Starting document ingestion pod'
                    dir("${PROJECT_NAME}/${AI_SERVICES_DIR}") {
                        sh "${AI_SERVICES_BINARY} application start ${APP_NAME} --pod=${APP_NAME}--ingest-docs -y"
                    }
                }
            }
            post {
                success {
                    script {
                        def hostname = sh(script: "hostname -I | awk '{print \$1}'", returnStdout: true).trim()
                        def message = """
                        Application is deployed and document is ingested.
                            *Chat bot URL:* http://${hostname}:${env.RAG_CHAT_BOT_PORT}
                        """
                        sendSlackNotification('good', message)
                    }
                }
            }
        }

        stage('Test Deployment') {
            steps{
                script{
                    // Polling to check if app is deleted
                    for (int i = 0; i < env.MAX_APP_RUN_TIME_IN_MINS.toInteger() ; i++) {
                        def appName = getDeployedAppName()
                        if (appName.isEmpty()) {
                            break
                        }
                        println "Iteration number ${i}, waiting for 60s"
                        sh 'sleep 60s'
                    }
                }
            }
        }
    }
    post {
        always {
            // Cleanup app deployed by the pipeline
            script {
                deleteCicdApp()
            }
        }
        failure {
            script{
                sendSlackNotification('danger', 'Jenkins PR preview pipeline job has been failed with an error.')
            }
        }
        success {
            script {
                sendSlackNotification('good', 'Jenkins PR preview pipeline job has been completed.')
            }
        }
        aborted {
            script{
                sendSlackNotification('warning', 'Jenkins PR preview pipeline job has been aborted.')
            }
        }
    }
}

def sendSlackNotification(String color, String message) {
    def hostname = sh(
        script: "hostname -I | awk '{print \$1}'",
        returnStdout: true
    ).trim()
    
    slackSend(
        channel: "${env.SLACK_NOTIFICATION_CHANNEL}",
        teamDomain: "$TEAM_DOMAIN",
        tokenCredentialId: 'slack',
        color: "${color}",
        message: """
        ${message}
            *Job Name      :* ${env.JOB_NAME}
            *Build Number  :* ${env.BUILD_NUMBER}
            *Build URL.    :* ${env.BUILD_URL}
            *Host          :* ${hostname}
            *CommitHash/PR :* ${params.CHECKOUT}
        """.stripIndent()
    )
}

// Returning app name which is deployed in the machine
def getDeployedAppName() {
    String appName = ''
    dir("${env.PROJECT_NAME}/${env.AI_SERVICES_DIR}") {
        def apps = sh(
            script: "${AI_SERVICES_BINARY} application ps 2>&1",
            returnStdout: true
        ).trim()
        def outputLines = apps.readLines()
        if (outputLines.size() > 2 ) {
            appName = outputLines[2].split()[0]
            println "Application: '${appName}' is deployed."
        }
    }
    return appName
}

def repoCheckout(String branch) {
    sh "git clone ${env.AI_SERVICES_REPO_URL}"
    dir("${PROJECT_NAME}") {
        if (branch ==~ /^\d+$/) {
            println "Checking out to ${branch} PR number"
            sh """
                git fetch origin pull/${branch}/head:pr-${branch}
                git checkout pr-${branch}
            """
        } else {
            println "Checking out to ${branch} commit hash"
            sh "git rev-parse --verify ${branch}"
            sh "git checkout ${branch}"
        }
    }
}

// Delete application deployed via CI/CD pipeline
def deleteCicdApp() {
    String appName = getDeployedAppName()
    dir("${env.PROJECT_NAME}/${env.AI_SERVICES_DIR}") {
        if (appName.contains('cicd')) {
            println "Cleaning up ${appName} which is deployed by pipelines."
            sh "${AI_SERVICES_BINARY} application delete ${appName} -y"
        }
    }
}

def isFileUpdated(String path) {
    def isfileChanged = false
    dir("${PROJECT_NAME}") {
        def changedFiles = sh(
            script: 'git diff --name-only origin/main...HEAD',
            returnStdout: true
        ).trim().split('\n')
        println "Modified files list: ${changedFiles}"
        isfileChanged = changedFiles.any{ it.startsWith(path)}
    }
    return isfileChanged
}

def buildImage(String imageName, String containerFilePath) {
    String localRegistry = 'localhost'
    String imagePath = ""
    dir(env.PROJECT_NAME) {
        dir(containerFilePath) {
            sh "make build REGISTRY=${localRegistry}"

            def tag = sh(script: "make image-tag REGISTRY=${localRegistry}", returnStdout: true).trim()
            imagePath = "${localRegistry}/${imageName}:${tag}"
            println "Successfully built ${imagePath} on the machine"
        }
    }
    return imagePath
}

def getModifiedApp() {
    // Contains list of supported application and there file path
    def appList = [
        [appName: 'rag-dev', filePath: 'spyre-rag']
    ]

    def modifiedApp = ''
    for (app in appList) {
        def isChanged = isFileUpdated(app.filePath).toBoolean()
        if (isChanged) {
            println "Files are modified in path '${app.filePath}', therefore deploying '${app.appName}'"
            modifiedApp = app.appName
            break
        }
    }
    return modifiedApp
}

// Rebuilding modified images in the application
def buildAppImage(String appName) {
    if (appName == env.RAG_APP_NAME) {
        def imageMapList = [
            [imageName: 'rag-ui', filePath: 'spyre-rag/ui', jsonPath: '.ui.image'],
            [imageName: 'rag', filePath: 'spyre-rag/src', jsonPath: '.backend.image']
        ]

        for (imageInfo in imageMapList) {
            def isChanged = isFileUpdated(imageInfo.filePath).toBoolean()
            if (isChanged) {
                println "Rebuilding ${imageInfo.imageName} for deployment"
                String imageVal = buildImage(imageInfo.imageName, imageInfo.filePath)
                updateYamlFile(env.RAG_APP_NAME, imageVal, imageInfo.jsonPath)
            }else {
                println "No changes in ${imageInfo.imageName} image"
            }
        }
    } else {
        error("Selected ${appName} not supported.")
    }
}


// Method to update local image in the yaml file
// so that deployment of local image is done
def updateYamlFile(String appName, String imageValue, String overridePath) {
    dir(env.PROJECT_NAME) {
        String valuesFile = "ai-services/assets/applications/${appName}/podman/values.yaml"
        if (!fileExists(valuesFile)) {
            error("no values.yaml for ${appName}")
            return
        }
        sh "yq e '${overridePath} = \"${imageValue}\"' -i ${valuesFile}"
        println "Values.yaml is updated in ${appName} for parameter ${overridePath} with value ${imageValue}"
    }
}
