apiVersion: batch/v1
kind: CronJob
metadata:
  name: "ingest-docs"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  schedule: "0 0 1 1 *" # never runs as suspend is set to true
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: ingest-docs
              image: "{{ .Values.backend.image }}"
              command:
                - "/var/venv/bin/python"
                - "-m"
                - "ingest.cli"
                - "ingest"
              resources:
                requests:
                  cpu: "1"
                  memory: "50Gi"
                limits:
                  cpu: "1"
                  memory: "50Gi"
              env:
                - name: EMB_ENDPOINT
                  value: http://embedding-predictor:8080
                - name: EMB_MODEL
                  value: ibm-granite/granite-embedding-278m-multilingual
                - name: EMB_MAX_TOKENS
                  value: "512"
                - name: LLM_ENDPOINT
                  value: http://instruct-predictor:8000
                - name: LLM_MODEL
                  value: ibm-granite/granite-3.3-8b-instruct
                - name: OPENSEARCH_HOST
                  value: "opensearch"
                - name: OPENSEARCH_PORT
                  value: "9200"
                - name: OPENSEARCH_DB_PREFIX
                  value: "RAG_DB"
                - name: OPENSEARCH_INDEX_NAME
                  value: "RAG_INDEX"
                - name: OPENSEARCH_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: "opensearch-credentials"
                      key: username
                - name: OPENSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: "opensearch-credentials"
                      key: password
                - name: LOG_LEVEL
                  value: "{{ .Values.ingest.log_level}}"
              volumeMounts:
                - name: docs
                  mountPath: /var/docs
                  readOnly: true
                - name: cache
                  mountPath: /var/cache
          restartPolicy: Never
          volumes:
            - name: docs
              persistentVolumeClaim:
                claimName: "docs"
            - name: cache
              persistentVolumeClaim:
                claimName: "cache"
