apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "opensearch"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
