apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch-sa
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
