apiVersion: v1
kind: Service
metadata:
  name: "ui"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
spec:
  selector:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/component: ui
  ports:
    - name: ui
      port: 3000
      targetPort: 3000
      protocol: TCP
