name: AI Services
on:
  push:
    paths:
      - 'ai-services/**'
    branches:
      - main
      - 'release-*'
  pull_request:
    paths:
      - 'ai-services/**'
      - .github/workflows/ai-services-image.yml

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-publish-image:
    name: Build and Publish Image
    uses: ./.github/workflows/build-and-publish-image.yml
    with:
      working-directory: 'ai-services'
    secrets: inherit

  scan:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'ai-services'
      image: 'ai-services'
