name: Caddy webserver
on:
  push:
    paths:
      - 'images/caddy/**'
    branches:
      - main
      - 'release-*'
  pull_request:
    paths:
      - 'images/caddy/**'
      - '.github/workflows/caddy-image.yml'
    branches:
      - main
      - 'release-*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-publish-image:
    name: Build and Publish Image
    uses: ./.github/workflows/build-and-publish-image.yml
    with:
      working-directory: 'images/caddy'
    secrets: inherit

  scan:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'images/caddy'
      image: 'caddy'
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}
