name: Chatbot UI
on:
  push:
    paths:
      - 'ui/chatbot/**'
    branches:
      - main
      - 'release-*'
  pull_request:
    paths:
      - 'ui/chatbot/**'
      - .github/workflows/chatbot-ui.yml

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  format:
    name: format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ui/chatbot/package-lock.json

      - name: Install dependencies
        working-directory: ui/chatbot
        run: npm ci

      - name: Run Prettier check
        working-directory: ui/chatbot
        run: npm run format:check

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ui/chatbot/package-lock.json

      - name: Install dependencies
        working-directory: ui/chatbot
        run: npm ci

      - name: Run linter
        working-directory: ui/chatbot
        run: npm run lint

  build-publish-image:
    name: Build and Publish Image
    needs: [lint, format]
    uses: ./.github/workflows/build-and-publish-image.yml
    with:
      working-directory: 'ui/chatbot'
    secrets: inherit

  scan:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'ui/chatbot'
      image: 'chatbot-ui'
