name: Digitize UI
on:
  push:
    paths:
      - 'ui/digitize/**'
    branches:
      - main
      - 'release-*'
  pull_request:
    paths:
      - 'ui/digitize/**'
      - .github/workflows/digitize-ui-image.yml
    branches:
      - main
      - 'release-*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ui/digitize/package-lock.json

      - name: Install dependencies
        working-directory: ui/digitize
        run: npm ci

      - name: Run linter
        working-directory: ui/digitize
        run: npm run lint

  build-publish-image:
    name: Build and Publish Image
    needs: [lint]
    uses: ./.github/workflows/build-and-publish-image.yml
    with:
      working-directory: 'ui/digitize'
    secrets: inherit

  scan:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'ui/digitize'
      image: 'digitize-ui'

# Made with Bob
