name: Scheduled CVE and Licenses Scan

on:
  # Added pull_request_target to validate PR commit, will remove it.
  pull_request_target:
  schedule:
    - cron: '0 0 */2 * *'

  workflow_dispatch:
    inputs:
      skip-cves-scan:
        description: Skips cves scan job when variable is set to true.
        required: false
        type: boolean
        default: false
      skip-license-scan:
        description: Skips license scan job when variable is set to true.
        required: false
        type: boolean
        default: false

jobs:
  rag-base:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'images/rag-base'
      image: 'rag-base'
      skip-image-build: true
      ignore-unfixed: false
      skip-cves-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-cves-scan }}
      skip-license-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-license-scan }}
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}

  rag:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'spyre-rag/src'
      image: 'rag'
      skip-image-build: true
      ignore-unfixed: false
      skip-cves-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-cves-scan }}
      skip-license-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-license-scan }}
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}

  rag-ui:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'spyre-rag/ui'
      image: 'rag-ui'
      skip-image-build: true
      ignore-unfixed: false
      skip-cves-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-cves-scan }}
      skip-license-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-license-scan }}
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}

  tools:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'images/tools'
      image: 'tools'
      skip-image-build: true
      ignore-unfixed: false
      skip-cves-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-cves-scan }}
      skip-license-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-license-scan }}
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}

  vllm-ppc64le:
    uses: ./.github/workflows/scanner.yml
    with:
      registry-image: 'icr.io/ppc64le-oss/vllm-ppc64le:latest'
      image: 'vllm-ppc64le'
      ignore-unfixed: false
      skip-cves-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-cves-scan }}
      skip-license-scan: true
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}

  opensearch:
    uses: ./.github/workflows/scanner.yml
    with:
      registry-image: 'icr.io/ai-services-private/opensearch:latest'
      image: 'opensearch'
      ignore-unfixed: false
      skip-cves-scan: ${{ github.event_name == 'workflow_dispatch' && inputs.skip-cves-scan }}
      skip-license-scan: true
    secrets:
      ICR_USERNAME: ${{ secrets.ICR_USERNAME }}
      ICR_APIKEY: ${{ secrets.ICR_APIKEY }}
