name: Minio
on:
  push:
    paths:
      - 'images/minio/**'
    branches:
      - main
  pull_request:
    paths:
      - 'images/minio/**'
    branches:
      - main

env:
  ICR_REGISTRY: icr.io
  ICR_NAMESPACE: ai-services-cicd
  IMAGE_FILE_NAME: image.tar

jobs:
  build-publish-image:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Create file
        run: echo -e "Line 1\nLine 2\nLine 3" > trivy-result.txt

      - name: Trivy result
        id: trivy-report
        run: |
          cat trivy-result.txt
          echo "result=$(cat trivy-result.txt)" >> $GITHUB_OUTPUT

      - name: Notify Vulnerabilities via PR Comment
        uses: hasura/comment-progress@v2.3.0
        
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.pull_request.number }}
          id: trivy-scan-result
          message: ${{ steps.trivy-report.outputs.result }}
      
      - name: Print out variable
        run: echo "${{ steps.trivy-report.outputs.result }}"
          
      - name: Fail the build if vulnerabilities found
        if: ${{ steps.trivy.outcome == 'failure' }}
        run: |
          echo -e "Vulnerabilities found in the image. Failing the build."
          exit 1
          
      - name: Publish minio image
        working-directory: images/minio
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          make push REGISTRY=${{ env.ICR_REGISTRY }}/${{ env.ICR_NAMESPACE }} REGISTRY_USER=${{ secrets.ICR_USERNAME }} REGISTRY_PASSWORD=${{ secrets.ICR_APIKEY }}
