name: Postgres
on:
  push:
    paths:
      - 'images/postgres/**'
    branches:
      - main
      - 'release-*'
  pull_request:
    paths:
      - 'images/postgres/**'
      - .github/workflows/postgres-image.yml
    branches:
      - main
      - 'release-*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-publish-image:
    name: Build and Publish Image
    uses: ./.github/workflows/build-and-publish-image.yml
    with:
      working-directory: 'images/postgres'
    secrets: inherit

  scan:
    uses: ./.github/workflows/scanner.yml
    with:
      path: 'images/postgres'
      image: 'postgres'

# Made with Bob
